#!/bin/sh

set -e

check_divert() {
	if [ -z "$(dpkg-divert --list $1)" ]; then
		dpkg-divert --add --package mx-antix-libs --rename \
		  --divert $1.distrib $1
	fi
}

if [ "$1" = "install" ] || [ "$1" = "upgrade" ]
then
  check_divert /usr/local/lib/antiX/antiX-style-default.sh
  check_divert /usr/local/lib/antiX/antiX-common.sh
fi
