#!/bin/sh

set -e

remove_divert() {
  if [ ! -z "$(dpkg-divert --list $1)" ]; then
    dpkg-divert --remove --package mx-antix-libs --rename \
      --divert $1.distrib $1
  fi
}

if [ "$1" = "remove" ]; then
  remove_divert /usr/local/lib/antiX/antiX-style-default.sh
  remove_divert /usr/local/lib/antiX/antiX-common.sh
fi
